### PR TITLE
Change collation of ID columns in permission backend to speed up delete_object_permissions

### LINKED ISSUE #1460: Flushing a server breaks migration forever
Using the Kinto `flush` plugin wipes the metadata table, which removes information about the storage schema version. This means it is impossible to do a migration, because we no longer have any idea what version to migrate *from*.

There is currently error-handling logic which tries to accommodate for this. It assumes that 1. if the metadata table is empty, then the server was flushed, and 2. if the server was flushed, the schema version in-place is the "current" maximal one. Point 2 is obviously wrong in the case of e.g. local development, where you might flush the server and then, much later, try to build and run a new Kinto version. Point 1 is about to become wrong as we add migration to the permission backend, which may store data in the same metadata table. On top of all of this, the code is not clearly marked as error-handling logic, although it really is.

### PR DESCRIPTION
**Pull request by glasserc**
Fixes #1460.

- [x] Reuse migration mechanism to cover permission backend.
- [x] Actually add a migration for the permission backend adding COLLATE "C" to tables that need it.
- [x] Add documentation.
- [x] Add tests.
- [x] Add a changelog entry.
- [x] Add your name in the contributors file.
- (n/a) If you changed the HTTP API, update the [API_VERSION](https://github.com/Kinto/kinto/blob/master/kinto/__init__.py#L15) constant and add an API changelog entry [in the docs](https://github.com/Kinto/kinto/blob/master/docs/api/index.rst)
- (n/a) If you added a new configuration setting, update the [`kinto.tpl`](https://github.com/Kinto/kinto/blob/master/kinto/config/kinto.tpl) file with it.

### CODE REVIEW

**Comment by glasserc** [comment]
/cc @peterbe. If you were interested in getting your hands dirty in the Kinto codebase, this might be a PR to look at.

I'm not exactly sure what the test failure is about, but some of these tests seem to take a strange attitude about cleaning up after themselves -- looking at it now.

**Comment by Natim** [comment]
Adding @leplatrem let's try to pair review it tomorrow

File: kinto/core/permission/postgresql/schema.sql [hunk 1]
```diff
@@ -4,14 +4,14 @@
 SET client_min_messages TO ERROR;
 
 CREATE TABLE IF NOT EXISTS user_principals (
-    user_id TEXT,
+    user_id TEXT COLLATE "C",
```
Comment (peterbe) [inline kinto/core/permission/postgresql/schema.sql]: Would be nice with a comment here that justifies this hack.

File: kinto/core/permission/postgresql/schema.sql [hunk 2]
```diff
@@ -4,14 +4,14 @@
...
     principal TEXT,
 
     PRIMARY KEY (user_id, principal)
 );
 
 CREATE TABLE IF NOT EXISTS access_control_entries (
-    object_id TEXT,
+    object_id TEXT COLLATE "C",
```
Comment (peterbe) [inline kinto/core/permission/postgresql/schema.sql]: ditto

File: kinto/core/permission/postgresql/__init__.py [hunk 3]
```diff
@@ -5,12 +5,15 @@
 
 from kinto.core.permission import PermissionBase
 from kinto.core.storage.postgresql.client import create_from_config
+from kinto.core.storage.postgresql.migrator import Migrator
 
 
 logger = logging.getLogger(__name__)
 
+HERE = os.path.abspath(os.path.dirname(__file__))
```
Comment (peterbe) [inline kinto/core/permission/postgresql/__init__.py]: Why the `os.path.abspath`? `os.path.dirname` should always give a valid directory path.

File: kinto/core/permission/postgresql/__init__.py [hunk 4]
```diff
@@ -77,23 +136,12 @@ def initialize_schema(self, dry_run=False):
...
-        # Since called outside request, force commit.
-        with open(sql_file) as f:
-            schema = f.read()
-        with self.client.connect(force_commit=True) as conn:
-            conn.execute(schema)
-        logger.info('Created PostgreSQL permission tables')
+        # Metadata table missing or has no
+        # permission_schema_version, and no user_principals table. We
+        # need to initialize.
+        return None
```
Comment (peterbe) [inline kinto/core/permission/postgresql/__init__.py]: nit: Ending a function without `return None` is the same as ending the function with a `return None`.

File: kinto/core/permission/postgresql/migrations/migration_001_002.sql [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+    value VARCHAR(512) NOT NULL
+);
+
+ALTER TABLE user_principals
+    ALTER COLUMN user_id TYPE TEXT COLLATE "C";
+
+ALTER TABLE access_control_entries
+    ALTER COLUMN object_id TYPE TEXT COLLATE "C";
+
+INSERT INTO metadata VALUES ('permission_schema_version', '2');
```
Comment (peterbe) [inline kinto/core/permission/postgresql/migrations/migration_001_002.sql]: nit: If the `metadata` table already existed, it's not a guarantee that the column order is exactly `'name', 'value'`. A safer INSERT statement would be:
`INSERT INTO metadata (name, value) VALUES ('permission_schema_version', '2');`

File: tests/core/schema/postgresql-permission-1.sql [hunk 6]
```diff
@@ -0,0 +1,20 @@
+CREATE TABLE IF NOT EXISTS user_principals (
+    user_id TEXT,
```
Comment (peterbe) [inline tests/core/schema/postgresql-permission-1.sql]: I'm confused. Why isn't this `COLLATE "C"` too?

File: kinto/core/storage/postgresql/migrator.py [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+A helper class to run migrations using a series of SQL files.
+"""
+
+import logging
+import os
+
+logger = logging.getLogger(__name__)
+
+
+class Migrator(object):
```
Comment (peterbe) [inline kinto/core/storage/postgresql/migrator.py]: No need to `(object)` in any py 3 code.

Comment (peterbe) [reply kinto/core/storage/postgresql/migrator.py]: Also, is `MigratorMixin` a better name to indicate to the code reader how you're supposed to use this?

File: kinto/core/storage/postgresql/migrator.py [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+    migrations_directory = None
+
+    def _get_installed_version(self):
+        """Return current version of schema or None if none found.
+
+        Override this.
+
+        This may be called several times during a single migration.
+        """
+        pass
```
Comment (peterbe) [inline kinto/core/storage/postgresql/migrator.py]: This should probably be `raise NotImplementedError('method not overwritten')`

File: kinto/core/storage/postgresql/migrator.py [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+    """The file to find the current "newest" schema in. Override this."""
+    schema_file = None
+
+    """The directory to find migration files in.
+
+    Migrations should each be a file named migration_nnn_mmm.sql, where mmm = nnn + 1.
+    """
+    migrations_directory = None
+
+    def _get_installed_version(self):
```
Comment (peterbe) [inline kinto/core/storage/postgresql/migrator.py]: Weird that a privately named method is expected to be overridden.

File: kinto/core/storage/postgresql/migrator.py [hunk 10]
```diff
@@ -0,0 +1,95 @@
...
+            self.create_schema(dry_run)
+            return
+
+        logger.info('Detected PostgreSQL {} schema version {}.'.format(self.name, version))
+        if version == self.schema_version:
+            logger.info('PostgreSQL {} schema is up-to-date.'.format(self.name))
+            return
+
+        self.migrate_schema(version, dry_run)
+        return
```
Comment (peterbe) [inline kinto/core/storage/postgresql/migrator.py]: not necessary

File: tests/core/test_storage_migrations.py [hunk 11]
```diff
@@ -8,9 +8,72 @@
...
 from kinto.core.permission import postgresql as postgresql_permission
 from kinto.core.storage import postgresql as postgresql_storage
+from kinto.core.storage.postgresql.migrator import Migrator
 from kinto.core.testing import skip_if_no_postgresql
 
 
+class MigratorTest(unittest.TestCase):
+    def __init__(self, *args, **kwargs):
+        super().__init__(*args, **kwargs)
+        self.migrator = Migrator()
```
Comment (peterbe) [inline tests/core/test_storage_migrations.py]: This looks dangerous. You create an instance of `Migrator` but mutate it within the tests. 
It'd be much better to ...:
```python
    def setUp(self):
        self.migrator = Migrator()
        ...
```

File: tests/core/test_storage_migrations.py [hunk 12]
```diff
@@ -8,9 +8,72 @@
...
+    def test_migration_files_are_listed_if_ran_with_dry_run(self):
+        self.migrator.schema_version = 6
+
+        versions = [6, 5, 4, 3, 3]
+        self.migrator._get_installed_version = lambda: versions.pop()
+
+        with mock.patch('kinto.core.storage.postgresql.migrator.logger') as mocked:
+            self.migrator.create_or_migrate_schema(dry_run=True)
+
+        output = ''.join([repr(call) for call in mocked.info.call_args_list])
```
Comment (peterbe) [inline tests/core/test_storage_migrations.py]: Why `repr()`? Won't it already be a perfectly fine string object?

File: tests/core/test_storage_migrations.py [hunk 13]
```diff
@@ -8,9 +8,72 @@
...
+        sql_called = execute_sql.call_args_list[-1][0][0]
+        self.assertIn('migrations/migration_005_006.sql', sql_called)
+
+    def test_migration_files_are_listed_if_ran_with_dry_run(self):
+        self.migrator.schema_version = 6
+
+        versions = [6, 5, 4, 3, 3]
+        self.migrator._get_installed_version = lambda: versions.pop()
+
+        with mock.patch('kinto.core.storage.postgresql.migrator.logger') as mocked:
```
Comment (peterbe) [inline tests/core/test_storage_migrations.py]: Arguably, perhaps all logging you should be captured. E.g.

```python
    @mock.patch('kinto.core.storage.postgresql.migrator.logger')
    def setUp(self, mocked_logger):
        self.migrator = Migrator()
        self.mocked_logger = mocked_logger
```

File: tests/core/test_storage_migrations.py [hunk 14]
```diff
@@ -8,9 +8,72 @@
...
+                self.migrator.create_or_migrate_schema()
+                self.assertFalse(execute_sql.called)
+
+    def test_migration_file_is_executed_for_every_intermediary_version(self):
+        self.migrator.schema_version = 6
+
+        versions = [6, 5, 4, 3, 3]
+        self.migrator._get_installed_version = lambda: versions.pop()
+
+        with mock.patch.object(self.migrator, '_execute_sql_file') as execute_sql:
```
Comment (peterbe) [inline tests/core/test_storage_migrations.py]: This is now repeated in 3 of the 5 tests so it should probably be mocked in the `setUp` method.

File: kinto/core/permission/postgresql/__init__.py (hunk 3 above)
Comment (peterbe) [reply kinto/core/permission/postgresql/__init__.py]: What I mean is; If there's a strong reason for using `os.path.abspath` it should be a code comment that explains why. If there isn't a reason, it can be deleted and only use `os.path.dirname(__file__)`.

File: kinto/core/permission/postgresql/__init__.py [hunk 15]
```diff
@@ -63,12 +66,68 @@ class Permission(PermissionBase):
...
+              FROM metadata
+             WHERE name = 'permission_schema_version'
+             ORDER BY LPAD(value, 3, '0') DESC
+             LIMIT 1;
+            """
+            with self.client.connect() as conn:
+                result = conn.execute(query)
+                if result.rowcount > 0:
+                    return int(result.fetchone()['version'])
+
```
Comment (peterbe) [inline kinto/core/permission/postgresql/__init__.py]: Indent this whole block one to the right and avoid the second connection creation.

File: kinto/core/storage/postgresql/__init__.py [hunk 16]
```diff
@@ -8,13 +8,15 @@
     DEFAULT_ID_FIELD, DEFAULT_MODIFIED_FIELD, DEFAULT_DELETED_FIELD,
     MISSING)
 from kinto.core.storage.postgresql.client import create_from_config
+from kinto.core.storage.postgresql.migrator import Migrator
 from kinto.core.utils import COMPARISON
 
 
 logger = logging.getLogger(__name__)
+HERE = os.path.abspath(os.path.dirname(__file__))
```
Comment (peterbe) [inline kinto/core/storage/postgresql/__init__.py]: ditto about use of `abspath`

File: kinto/core/permission/postgresql/__init__.py (hunk 3 above)
Comment (glasserc) [reply kinto/core/permission/postgresql/__init__.py]: Apparently as of Python 3.4, `__file__` is almost always an absolute path. I have updated the uses of it in the codebase.

File: kinto/core/permission/postgresql/__init__.py (hunk 4 above)
Comment (glasserc) [reply kinto/core/permission/postgresql/__init__.py]: While this is technically true, I believe returning `None` explicitly in this particular case is a better expression of intent here, since the function is meant to return None when it cannot identify the schema version in play. But I agree with your suggestion in a couple of other places.

File: tests/core/schema/postgresql-permission-1.sql (hunk 6 above)
Comment (glasserc) [reply tests/core/schema/postgresql-permission-1.sql]: This is the original schema, from which I want to verify that migration is possible.

File: tests/core/test_storage_migrations.py (hunk 11 above)
Comment (glasserc) [reply tests/core/test_storage_migrations.py]: Oops, yeah. Good catch. I hate XUnit-style test cases..

File: tests/core/test_storage_migrations.py (hunk 12 above)
Comment (glasserc) [reply tests/core/test_storage_migrations.py]: Each call is a tuple of arguments. I guess the idea is to make sure that forms such as `logger.info("Executing migration {}", "migrations/migration_003_004.sql")` are still OK?

File: tests/core/test_storage_migrations.py (hunk 13 above)
Comment (glasserc) [reply tests/core/test_storage_migrations.py]: Rethinking how logging is done in the test suite is outside the scope of this PR, although I agree it needs work.

**Comment by glasserc** [comment]
Thanks for the suggestions -- I'll try to clean up the mocking in the test cases tomorrow.

File: kinto/core/permission/postgresql/__init__.py [hunk 17]
```diff
@@ -63,12 +66,68 @@ class Permission(PermissionBase):
...
+        Migrations were only added to the permission backend in
+        8.1.2. Before this, the permission backend was only the two
+        tables ``user_principals`` and ``access_control_entries``. The
+        presence of these two tables and absence of a metadata
+        table/permission_schema_version is therefore version 1.
+
+        In version 8.1.2, the permission backend added a ``metadata``
+        table. If the permission and storage backends share
+        credentials, this will be the same table created by the
```
Comment (leplatrem) [inline kinto/core/permission/postgresql/__init__.py]: nit: *share credentials* → *share the same database* ?

File: kinto/core/storage/postgresql/__init__.py [hunk 18]
```diff
@@ -157,48 +118,68 @@ def _check_database_encoding(self):
...
-        """Delete records from tables without destroying schema. Mainly used
-        in tests suites.
+        """Delete records from tables without destroying schema.
+
+        This is used in test suites as well as in the flush plugin.
         """
         query = """
         DELETE FROM records;
         DELETE FROM timestamps;
-        DELETE FROM metadata;
```
Comment (leplatrem) [inline kinto/core/storage/postgresql/__init__.py]: So this fixes #1460

File: tests/core/schema/postgresql-permission-1.sql [hunk 19]
```diff
@@ -0,0 +1,20 @@
...
+    principal TEXT,
+
+    PRIMARY KEY (object_id, permission, principal)
+);
+CREATE INDEX IF NOT EXISTS idx_access_control_entries_object_id
+    ON access_control_entries(object_id);
+CREATE INDEX IF NOT EXISTS idx_access_control_entries_permission
+  ON access_control_entries(permission);
+CREATE INDEX IF NOT EXISTS idx_access_control_entries_principal
+  ON access_control_entries(principal);
```
Comment (leplatrem) [inline tests/core/schema/postgresql-permission-1.sql]: You might want to add a row in metadata here.

File: kinto/core/permission/postgresql/migrations/migration_001_002.sql [hunk 20]
```diff
@@ -0,0 +1,18 @@
...
+-- migration status for both. Only one schema actually has to create
+-- it.
+CREATE TABLE IF NOT EXISTS metadata (
+    name VARCHAR(128) NOT NULL,
+    value VARCHAR(512) NOT NULL
+);
+
+-- IDs are not really human language text, so set them to be COLLATE
+-- "C" rather than the DB default collation. This also speeds up
+-- prefix-match queries (object_id LIKE '/bucket/abc/%').
```
Comment (peterbe) [inline kinto/core/permission/postgresql/migrations/migration_001_002.sql]: 👍

File: tests/core/schema/postgresql-permission-1.sql (hunk 19 above)
Comment (glasserc) [reply tests/core/schema/postgresql-permission-1.sql]: That would create a schema that was different from the PostgreSQL permission v1 schema.

File: kinto/core/storage/postgresql/__init__.py (hunk 18 above)
Comment (glasserc) [reply kinto/core/storage/postgresql/__init__.py]: Yes (as described in the PR description as well as the commit comments).
